version: '3.9'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 3000:3000
